networks:
  krr_tool_network:
    driver: bridge

services:
  rdfox-db:
    build:
      context: .
      dockerfile: rdfox_db/Dockerfile
    volumes:
      - ./rdfox_db/src/data:/var/lib/RDFox  # Mounting host's rdfox_db/src/data directory to container's /var/lib/RDFox
    ports:
      - "12110:12110"  # Map the port
    environment:
      - RDFOX_ROLE=admin
      - RDFOX_PASSWORD=password
      - RDFOX_ENDPOINT=http://rdfox-db:12110
      - RDFOX_DSTORE=test_store
    networks:
      - krr_tool_network

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    depends_on:
      - rdfox-db
    env_file:
      - .env
    networks:
      - krr_tool_network
    volumes:
    - ./rdfox_db/src/data:/var/lib/RDFox  # Ensure it can read the RDFox setup complete status
    ports:
      - "8000:8000"