networks:
  krr_tool_network:
    driver: bridge

services:
  data-fetcher:
    build: 
      context: .
      dockerfile: data_fetcher/Dockerfile
    env_file:
      - .env

  data-sender:
    build: 
      context: .
      dockerfile: data_sender/Dockerfile
    env_file:
      - .env
  
  rdf-converter:
    build:
      context: .
      dockerfile: rdf_converter/Dockerfile
   
  reverse-rdf-converter:
    build:
      context: .
      dockerfile: reverse_rdf_converter/Dockerfile
  
  rdfox-db:
    build:
      context: .
      dockerfile: rdfox_db/Dockerfile
    volumes:
      - ./rdfox_db/src/data:/var/lib/RDFox  # Mounting host's rdfox_db/src/data directory to container's /var/lib/RDFox
    ports:
      - "12110:12110"  # Map the port
    environment:
      - RDFOX_ROLE=admin
      - RDFOX_PASSWORD=password
      - RDFOX_ENDPOINT=http://rdfox-db:12110
      - RDFOX_DSTORE=test_store
    networks:
      - krr_tool_network

  processor:
    build:
      context: .
      dockerfile: processor/Dockerfile
    depends_on:
      - data-fetcher
      - rdfox-db
    env_file:
      - .env
    networks:
      - krr_tool_network
    volumes:
    - ./rdfox_db/src/data:/var/lib/RDFox  # Ensure it can read the RDFox setup complete status