#u rule fileu poglavlja 7 marko je napisao pomocna pravila za odredivanje coordination statusa - ona vec postoje u sekciji 2

# 5.7.1 Check which aircraft need to be transferred
SELECT ?flight ?aircraftNeedsToBeTransferredIndicator WHERE {?flight :aircraftNeedsToBeTransferred ?aircraftNeedsToBeTransferredIndicator}
SELECT ?flight ?warnATCOAboutXFLBeforeTransferringFlightIndicator WHERE {?flight :warnATCOAboutXFLBeforeTransferringFlight ?warnATCOAboutXFLBeforeTransferringFlightIndicator}
SELECT ?flight ?aircraftDoesNotNeedToBeTransfeeredIndicator WHERE {?flight :aircraftDoesNotNeedToBeTransfeered ?aircraftDoesNotNeedToBeTransfeeredIndicator}


# 5.7.2 Check if change of frequency is issued to A/C (via datalink)
SELECT ?flight ?changeOfFrequencyIssuedToACIndicator WHERE {?flight :changeOfFrequencyIssuedToAC ?changeOfFrequencyIssuedToACIndicator}

# 5.7.3 Change aircraft status to transferred 
SELECT ?flight ?coordinationStatusCanBeChangedToTransferredIndicator WHERE {?flight :coordinationStatusCanBeChangedToTransferred ?coordinationStatusCanBeChangedToTransferredIndicator}
